#!/bin/bash

ARGS="$@"
ICCARGS=""

# ./arch/x86/mm/ioremap.c: seems like a bug?
ARGS+=" -DCONFIG_ARCH_USE_MEMREMAP_PROT"

echo "DEBUG> ${ARGS}" > /dev/fd/2

for ARG in ${ARGS};
do
    case $ARG in
        -Wno-frame-address | -Wno-format-truncation | -Wno-format-overflow | -Wno-int-in-bool-context | -Wframe-larger-than=2048 | -Wno-unused-const-variable | -Wbad-function-cast | -Wformat-y2k | -Wnested-externs | -Wpacked | -Wredundant-decls | -Wswitch-default | -Wswitch-enum | -Wno-switch-default | -Wno-switch-enum | -Wno-packed )
            # Safe
            ;;
        -mno-mmx | -mno-3dnow | -funit-at-a-time | -ggdb3 | -fconserve-stack | -fno-inline-functions-called-once | -mskip-rax-setup | -mno-fp-ret-in-387 )
            # Seems safe (removing `-mno-fp-ret-in-387` is dangerous!)
            ;;
        -falign-jumps=1 )
            ICCARGS+=" -fno-align-loops"
            ;;
        -fno-stack-check )
            ICCARGS+=" -fno-stack-security-check"
            ;;
        -O6 )
            ICCARGS+=" -O3"
            ;;

        * )
            ICCARGS+=" $ARG"
            ;;
    esac
done

ICCARGS+=" -fno-strict-aliasing"
icc ${ICCARGS}
ret=$?

(( $ret == 0 )) && exit 0
echo ">>>>>icc-wrapper ${ARGS} <<<<<>>>>>icc ${ICCARGS} <<<<< failed with status $ret. Launching gcc..."  > /dev/fd/2
exit 111
gcc ${ARGS}
exit $?
